-- dumm_sql usage
-- 1) Run 01_schema.sql
-- 2) Edit and run 02_add_user.sql
-- 3) Edit and run 03_seed_profile_data.sql
-- 4) Create Supabase Auth users from site_user_emails (no manual dashboard step):
--    In your app folder run:
--      npm run auth:seed -- --password "YourStrongPassword123!"
--    Required env vars:
--      SUPABASE_SERVICE_ROLE_KEY
--      SUPABASE_URL (or VITE_SUPABASE_URL)
--
-- This folder is a reusable template for new users/projects.
