import type { PortfolioLanguage } from './supabase'

const en = { profile:'Profile',sections:'Sections',skills:'Skills',education:'Education',certifications:'Certifications',services:'Services & Testimonials',awards:'Awards & Recognition',experience:'Experience',contacts:'Contacts',projects:'Projects',repos:'Repositories',users:'Users',theme:'Theme',seo:'SEO & Sharing',analytics:'Analytics',backup:'Backup',exportCv:'Export CV',viewPortfolio:'View Portfolio',editPortfolio:'Edit Portfolio',signOut:'Sign Out',saved:'Saved!',displayName:'Display Name',titleRole:'Title / Role',bio:'Bio',avatarUrl:'Avatar URL',avatarManager:'Avatar Upload & Management',nationality:'Nationality',location:'Location',githubUsername:'GitHub Username',language:'Portfolio & Settings Language',saveProfile:'Save Profile',saving:'Saving...',about:'About Me',workExperience:'Work Experience',contact:'Contact',loading:'Loading...',servicesTitle:'Services',testimonials:'Testimonials',languages:'Languages' }
type Key = keyof typeof en
const dictionaries:Record<PortfolioLanguage,Partial<Record<Key,string>>> = {
 en,
 bn:{profile:'প্রোফাইল',sections:'সেকশন',skills:'দক্ষতা',education:'শিক্ষা',certifications:'সনদ',services:'সেবা ও প্রশংসাপত্র',awards:'পুরস্কার ও স্বীকৃতি',experience:'অভিজ্ঞতা',contacts:'যোগাযোগ',projects:'প্রকল্প',repos:'রিপোজিটরি',users:'ব্যবহারকারী',theme:'থিম',seo:'এসইও ও শেয়ারিং',analytics:'বিশ্লেষণ',backup:'ব্যাকআপ',exportCv:'সিভি এক্সপোর্ট',viewPortfolio:'পোর্টফোলিও দেখুন',editPortfolio:'পোর্টফোলিও সম্পাদনা',signOut:'সাইন আউট',saved:'সংরক্ষিত!',displayName:'প্রদর্শিত নাম',titleRole:'পদবি / ভূমিকা',bio:'পরিচিতি',avatarUrl:'ছবির URL',avatarManager:'ছবি আপলোড ও ব্যবস্থাপনা',nationality:'জাতীয়তা',location:'অবস্থান',githubUsername:'গিটহাব ব্যবহারকারীর নাম',language:'পোর্টফোলিও ও সেটিংসের ভাষা',saveProfile:'প্রোফাইল সংরক্ষণ',saving:'সংরক্ষণ হচ্ছে...',about:'আমার সম্পর্কে',workExperience:'কাজের অভিজ্ঞতা',contact:'যোগাযোগ',loading:'লোড হচ্ছে...',servicesTitle:'সেবা',testimonials:'প্রশংসাপত্র',languages:'ভাষা'},
 ja:{profile:'プロフィール',sections:'セクション',skills:'スキル',education:'学歴',certifications:'資格',services:'サービス・推薦文',awards:'受賞・表彰',experience:'職歴',contacts:'連絡先',projects:'プロジェクト',repos:'リポジトリ',users:'ユーザー',theme:'テーマ',seo:'SEO・共有',analytics:'分析',backup:'バックアップ',exportCv:'履歴書出力',viewPortfolio:'ポートフォリオを見る',editPortfolio:'ポートフォリオ編集',signOut:'ログアウト',saved:'保存しました',displayName:'表示名',titleRole:'肩書き / 役割',bio:'自己紹介',nationality:'国籍',location:'所在地',language:'表示言語',saveProfile:'プロフィールを保存',about:'自己紹介',workExperience:'職歴',contact:'連絡先'},
 zh:{profile:'个人资料',sections:'页面板块',skills:'技能',education:'教育经历',certifications:'证书',services:'服务与推荐',awards:'奖项与荣誉',experience:'工作经历',contacts:'联系方式',projects:'项目',repos:'代码仓库',users:'用户',theme:'主题',seo:'SEO 与分享',analytics:'数据分析',backup:'备份',exportCv:'导出简历',viewPortfolio:'查看作品集',editPortfolio:'编辑作品集',signOut:'退出登录',saved:'已保存',displayName:'显示名称',titleRole:'职位 / 角色',bio:'简介',nationality:'国籍',location:'所在地',language:'作品集与设置语言',saveProfile:'保存资料',about:'关于我',workExperience:'工作经历',contact:'联系我'},
 th:{profile:'โปรไฟล์',sections:'ส่วนต่าง ๆ',skills:'ทักษะ',education:'การศึกษา',certifications:'ใบรับรอง',services:'บริการและคำรับรอง',awards:'รางวัลและการยอมรับ',experience:'ประสบการณ์',contacts:'ช่องทางติดต่อ',projects:'โปรเจกต์',repos:'คลังโค้ด',users:'ผู้ใช้',theme:'ธีม',seo:'SEO และการแชร์',analytics:'การวิเคราะห์',backup:'สำรองข้อมูล',exportCv:'ส่งออก CV',viewPortfolio:'ดูพอร์ตโฟลิโอ',editPortfolio:'แก้ไขพอร์ตโฟลิโอ',signOut:'ออกจากระบบ',saved:'บันทึกแล้ว',displayName:'ชื่อที่แสดง',titleRole:'ตำแหน่ง / บทบาท',bio:'ประวัติย่อ',nationality:'สัญชาติ',location:'ที่อยู่',language:'ภาษาพอร์ตและการตั้งค่า',saveProfile:'บันทึกโปรไฟล์',about:'เกี่ยวกับฉัน',workExperience:'ประสบการณ์ทำงาน',contact:'ติดต่อ'},
 id:{profile:'Profil',sections:'Bagian',skills:'Keahlian',education:'Pendidikan',certifications:'Sertifikasi',services:'Layanan & Testimoni',awards:'Penghargaan & Pengakuan',experience:'Pengalaman',contacts:'Kontak',projects:'Proyek',repos:'Repositori',users:'Pengguna',theme:'Tema',seo:'SEO & Berbagi',analytics:'Analitik',backup:'Cadangan',exportCv:'Ekspor CV',viewPortfolio:'Lihat Portofolio',editPortfolio:'Edit Portofolio',signOut:'Keluar',saved:'Tersimpan!',displayName:'Nama Tampilan',titleRole:'Jabatan / Peran',bio:'Bio',nationality:'Kebangsaan',location:'Lokasi',language:'Bahasa Portofolio & Pengaturan',saveProfile:'Simpan Profil',about:'Tentang Saya',workExperience:'Pengalaman Kerja',contact:'Kontak'},
 ko:{profile:'프로필',sections:'섹션',skills:'기술',education:'학력',certifications:'자격증',services:'서비스 및 추천사',awards:'수상 및 표창',experience:'경력',contacts:'연락처',projects:'프로젝트',repos:'저장소',users:'사용자',theme:'테마',seo:'SEO 및 공유',analytics:'분석',backup:'백업',exportCv:'이력서 내보내기',viewPortfolio:'포트폴리오 보기',editPortfolio:'포트폴리오 편집',signOut:'로그아웃',saved:'저장됨!',displayName:'표시 이름',titleRole:'직함 / 역할',bio:'소개',nationality:'국적',location:'위치',language:'포트폴리오 및 설정 언어',saveProfile:'프로필 저장',about:'소개',workExperience:'경력',contact:'연락처'}
}
export const languageOf=(value?:string):PortfolioLanguage => ['en','bn','ja','zh','th','id','ko'].includes(value||'') ? value as PortfolioLanguage : 'en'
export const tr=(language:string|undefined,key:Key)=>dictionaries[languageOf(language)][key]||en[key]
