-- Privacy-friendly portfolio analytics. Safe to rerun.
CREATE TABLE IF NOT EXISTS public.portfolio_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portfolio_id integer NOT NULL REFERENCES public.portfolio_settings(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('view','project_click','contact_click','external_click')),
  target text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS portfolio_analytics_portfolio_created_idx ON public.portfolio_analytics(portfolio_id, created_at DESC);
ALTER TABLE public.portfolio_analytics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_insert_portfolio_analytics" ON public.portfolio_analytics;
CREATE POLICY "public_insert_portfolio_analytics" ON public.portfolio_analytics FOR INSERT TO anon, authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.portfolio_settings p WHERE p.id=portfolio_id AND p.is_published=true));
DROP POLICY IF EXISTS "owner_select_portfolio_analytics" ON public.portfolio_analytics;
CREATE POLICY "owner_select_portfolio_analytics" ON public.portfolio_analytics FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.portfolio_settings p WHERE p.id=portfolio_id AND (p.owner_id=public.current_site_user_id() OR public.is_site_admin())));
