import React, { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
type Method={id:string;platform_name:string;payment_url:string;account_name:string;description:string;icon_url:string;website_visible:boolean;api_visible:boolean;sort_order:number}
const blank=():Method=>({id:crypto.randomUUID(),platform_name:'',payment_url:'',account_name:'',description:'',icon_url:'',website_visible:true,api_visible:true,sort_order:0})
export default function EditDonations(){
 const [methods,setMethods]=useState<Method[]>([]),[originalIds,setOriginalIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{const {data,error}=await supabase.from('donation_methods').select('*').order('sort_order');if(error)return setMessage(error.message);const rows=(data||[]) as Method[];setMethods(rows);setOriginalIds(rows.map(x=>x.id))}
 useEffect(()=>{void load()},[])
 const update=(i:number,key:keyof Method,value:string|boolean)=>setMethods(rows=>rows.map((row,n)=>n===i?{...row,[key]:value}:row))
 const move=(i:number,d:number)=>setMethods(rows=>{const copy=[...rows],n=i+d;if(n<0||n>=copy.length)return rows;[copy[i],copy[n]]=[copy[n],copy[i]];return copy})
 const save=async()=>{setBusy(true);setMessage('');try{for(const row of methods){if(!row.platform_name.trim())throw new Error('Every method needs a platform name.');for(const value of [row.payment_url,row.icon_url].filter(Boolean)){const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw new Error('Links must use HTTP or HTTPS.')}}const removed=originalIds.filter(id=>!methods.some(row=>row.id===id));if(removed.length){const {error}=await supabase.from('donation_methods').delete().in('id',removed);if(error)throw error}if(methods.length){const {error}=await supabase.from('donation_methods').upsert(methods.map((row,i)=>({...row,sort_order:i})));if(error)throw error}await load();setMessage('Donation methods saved.')}catch(error){setMessage(error instanceof Error?error.message:'Could not save.')}finally{setBusy(false)}}
 return <div><h2>Global Donation Methods</h2><p className="edit-hint">One shared donation configuration is used across the entire website and every portfolio. Any administrator can maintain it; users never receive personal donation settings. Website and API visibility are separate.</p>{message&&<p className="admin-message">{message}</p>}
 {methods.map((row,i)=><div className="edit-edu-card donation-editor-card" key={row.id}><div className="admin-user-heading"><strong>{row.platform_name||`Method ${i+1}`}</strong><div className="avatar-actions"><button className="btn-outline" onClick={()=>move(i,-1)}>↑</button><button className="btn-outline" onClick={()=>move(i,1)}>↓</button><button className="edit-signout-btn" onClick={()=>setMethods(x=>x.filter((_,n)=>n!==i))}>Remove</button></div></div><div className="edit-form-grid">
 <div className="field"><label>Platform name</label><input value={row.platform_name} onChange={e=>update(i,'platform_name',e.target.value)}/></div><div className="field"><label>Account / username</label><input value={row.account_name} onChange={e=>update(i,'account_name',e.target.value)}/></div><div className="field field-full"><label>Payment URL</label><input type="url" value={row.payment_url} onChange={e=>update(i,'payment_url',e.target.value)}/></div><div className="field field-full"><label>Icon URL (optional)</label><input type="url" value={row.icon_url} onChange={e=>update(i,'icon_url',e.target.value)}/></div><div className="field field-full"><label>Description</label><textarea value={row.description} onChange={e=>update(i,'description',e.target.value)}/></div><label className="donation-check"><input type="checkbox" checked={row.website_visible} onChange={e=>update(i,'website_visible',e.target.checked)}/> Show on website</label><label className="donation-check"><input type="checkbox" checked={row.api_visible} onChange={e=>update(i,'api_visible',e.target.checked)}/> Include in API</label></div></div>)}
 <div className="donation-editor-actions"><button className="btn-outline" onClick={()=>setMethods(x=>[...x,blank()])}>+ Add Method</button><button className="btn-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save Methods'}</button></div></div>
}
